### PR TITLE
Another driver for riak cs, for small objects with multiple users

### PR DESCRIPTION
**Pull request by shino**
A basho_bench driver for load generating Riak CS, of second type.
First type driver (`basho_bench_driver_cs`) is good at load
generating with large HTTP payload. It has measurament option that
offer data transfer throughput like MB/sec.  On the other hand,
this driver's purpose is for small objects.  If the first type is
used for small objects, user and bucket objects can be hot keys in
Riak. This one can handle multiple users and buckets to avoid it.

Disclaimer (or future work):

This driver requires Riak CS is configured as `{admin_auth_enabled, false}`,
in order to automatically create users and buckets, also list users.
This can be avoided, for example, by reading local file of user list
create by `riak_cs_inspector`.

### CODE REVIEW

**Comment by kuenishi** [comment]
I thinks it's `{admin_auth_enabled, false}` that works for Riak CS.

**Comment by shino** [comment]
Oops, updated the description and pushed corrected source.

**Comment by kuenishi** [comment]
+1 as it worked fine. Great job!

**Comment by shino** [comment]
Some measurement with `riak_cs_yessir_riak_client`. These results were CPU saturated.

## put

```
                                Throughput ops/sec

  2500 ++-----+------+-----+------+------+------+------+-----+------+-----++
       +      +      +     +      +      +      +      +     +      +      +
       |A  AA A  AAA :AA A :  AA  A A    :      :A   A A A   : AA   :      |
  2000 ++.A....A.....A....A..A...A...AA.AA...AA.A..AA...A..AAA...A.AA.AA..++
       |      :      :     A      :      :      :      :     :      :      |
       |      :      :     :      :      :A A   :      :     :      :   A  |
       |      :      :     :      :      :      :      :     :      :      |
  1500 ++.................................................................++
       |      :      :     :      :      :      :      :     :      :      |
       |      :      :     :      :      :      :      :     :      :      |
  1000 ++.................................................................++
       |      :      :     :      :      :      :      :     :      :      |
       |      :      :     :      :      :      :      :     :      :      |
       |      :      :     :      :      :      :      :     :      :      |
   500 ++......................................current - successful...A...++
       |      :      :     :      :      :         current - failed   B    |
       +      +      +     +      +      +      +      +     +      +      +
     0 +B-BBB-BB-BBB-BBB-BBB-BBB-BB-BBB-BBB-BBB-BB-BBB-BBB-BBB-BBB-BB-BBB-++
       0      5      10    15     20     25     30     35    40     45     50
                                   Elapsed [sec]
```


## `get_existing`

```
                                Throughput ops/sec

  3000 ++-------+-------+--------+-------+--------+-------+--------+------++
       +        +       + A      +A      +        +       +        +       +
       | A      :  A  A A  A A A A  A A  :        :  A    :        :A A    |
  2500 ++.A.A.A.AA...A.................A...AA.A....A...AA.A....A.A.A....AA++
       |        :       :        :       A      A A       : A      :       |
       |        :       :        :       :        :       :  A     :       A
  2000 ++.................................................................++
       |        :       :        :       :        :       :        :       |
  1500 ++.................................................................++
       |        :       :        :       :        :       :        :       |
       |        :       :        :       :        :       :        :       |
  1000 ++.................................................................++
       |        :       :        :       :        :       :        :       |
       |        :       :        :       :        :       :        :       |
   500 ++......................................current - successful...A...++
       |        :       :        :       :         current - failed   B    |
       +        +       +        +       +        +       +        +       +
     0 ++BB-B-B-BB-B-BB-B-BB-B-B-BB-B-BB-B-BB-B-B-BB-B-BB-B-BB-B-B-BB-B-BB+B
       0        5       10       15      20       25      30       35      40
                                   Elapsed [sec]
```

**Pull request merged**
