### PR TITLE
Untangle basho_stats_writer and update travis

### PR DESCRIPTION
**Pull request by linearregression**
* untangle basho_stats_writer. csv and riemann writer no longer in one file.
* update travis.yml (at least one of pulled deps now require min erlang R16). Use travis container to build.

### CODE REVIEW

**Comment by slfritchie** [comment]
Hi, sorry about the delay in reviewing this PR!

The R16 minimum runtime requirement of the `quickrand` module is flawed.  As far as I can tell, the `random_wh06_int:uniform(5316911983139663491615228241121378304)` function works just fine when using R14B04, if I cut out the cruft that keeps quickrand from compiling at all.

    ^C250 [sbb4]:quickrand: env PATH=/usr/local/erlang/R14B04.64bit/bin:$PATH erl -pz ebin
    Erlang R14B04 (erts-5.8.5) [source] [64-bit] [smp:8:8] [rq:8] [async-threads:0] [hipe] [kernel-poll:false]
    
    Eshell V5.8.5  (abort with ^G)
    1> random_wh06_int:uniform(5316911983139663491615228241121378304).
    21209109798739021856976652074467755

I'm not a fan of forcing an Erlang runtime dependency change for basho_bench.  Do you have an alternate recommendation?

**Comment by linearregression** [comment]
The last travis CI build was ran 2yrs ago:
https://travis-ci.org/basho/basho_bench/branches

The majority of the PR si to untangle to stats backend.

So if you can make travisci run good again with R14 to R18. I can just merge with your branch or .master, then there is no need to remove R14 support.

**Comment by slfritchie** [comment]
{exasperation} ... the `katja` library uses a function name `query()`, which is a reserved word in Erlang R15.

**Comment by slfritchie** [comment]
See also, this commit after I merged this branch: https://github.com/basho/basho_bench/commit/f941cfd53184795561b4b299efbf89cfb6d192cc

Many thanks for the PR!

**Comment by linearregression** [comment]
Have you considered demoting the module using  kaja as contrb("use as at
your own risk")? The statsbackend is now untangled.

It does not look like katja is active in either branches. You just want to
post stats to Riemann server; does not look like you want any special
functionality from the library.

https://github.com/nifoc/katja/tree/development

**Comment by slfritchie** [comment]
Riemann is not my circus nor katja my monkey, sorry  If you have a PR in mind, I'll be happy to review it, but someone who's familiar with Riemann and the Riemann client library ecosystem should take a shot at this.  If it were me, I'd rip it out, so don't let me do it.  ^_^

**Pull request merged**
