### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by kuenishi**

### CODE REVIEW

**Comment by slfritchie** [comment]
Hi, Kota.  Are there any restrictions on the Erlang/OTP version(s) that these new package versions rely on?

**Comment by kuenishi** [comment]
I suppose all of them are within Riak, it is OK for OTP 17. I'm not sure about old one like R15.

**Comment by slfritchie** [comment]
Hi, Kota.  My apologies for overlooking this PR for so long.  AFAICT, the 'develop' tag on the 'riakc' dependency doesn't exist now.  What should it be?

    % cat .git/config
    [core]
    	repositoryformatversion = 0
    	filemode = true
    	bare = false
    	logallrefupdates = true
    	ignorecase = true
    	precomposeunicode = true
    [remote "origin"]
    	url = git://github.com/basho/riak-erlang-client
    	fetch = +refs/heads/*:refs/remotes/origin/*
    [branch "master"]
    	remote = origin
    	merge = refs/heads/master
    
    % git checkout master
    Already on 'master'
    Your branch is up-to-date with 'origin/master'.
    
    % git pull
    Already up-to-date.
    
    % git log | head -3
    commit 527722d12d0433b837cdb92a60900c2cb5df8942
    Author: Luke Bakken <luke@bakken.io>
    Date:   Wed Nov 11 08:29:45 2015 -0800
    
    % git checkout develop
    error: pathspec 'develop' did not match any file(s) known to git.

**Comment by kuenishi** [comment]
There used to be a 'develop' branch but it was somehow removed recently IIRC. These updates are pretty stale so that we'd better have another pull requests.

**Pull request closed without merging**
