### PR TITLE
Update required Erlang version

### PR DESCRIPTION
**Pull request by mrallen1**
Addresses #201 (RCS-348)

### CODE REVIEW

**Comment by kuenishi** [comment]
I think it was me who updated `required_otp_vsn` in rebar.config to `R16|17`. Do we still need to support R15?

**Comment by mrallen1** [comment]
For purely Basho projects, I doubt it. Not sure who out in the wide world might be affected though.

**Comment by slfritchie** [comment]
Hi, Mark.  Would you mind changing that README patch to version R16.  The `rebar.config` file mentions 3 dependent packages that have made R15 difficult without forking the !@#$! deps and fixing their incompatibilities.

**Comment by mrallen1** [comment]
Done @slfritchie

**Pull request merged**
